### ISSUE TITLE
Request info on the meta.text file

### ISSUE THREAD

**Issue by oualidbelhi01** [OmarBazaraa/WriterIdentifier#3]
Salut,je vous félicite pour votre projet,je voudrais demander informations sur le fichier texte meta. D’apres ce que j'ai constaté en lisant le code source,il contient une liste de dictionnaire{image path:id écrivain} et c'est celle rechargeable sur la plateforme IAM hors ligne.ZEt sur le code le fichier meta est vide et y a aucune instructions qui l’exécute pour l'écriture????

**Comment by OmarBazaraa** [comment]
Can you please write in English or Arabic?

**Comment by oualidbelhi01** [comment]
Hi, congratulations on your project, I would like to request information about the meta text file. From what I noticed while reading the source code, it contains a dictionnary list {image path: writer id} and it is the one reloadable on the offline IAM platform.  And on the code the file meta is empty and there is no instruction that executes it for writing ????

**Comment by oualidbelhi01** [comment]
Hi, congratulations on your project, I would like to request information about the meta text file. From what I saw while reading the source code, it contains a dictionnary list {image path: writer id} and it is the one reloadable on the offline IAM platform. And on the code the file meta is empty and there is no instruction that executes it for writing ????

**Comment by OmarBazaraa** [comment]
You should download the IAM dataset, both the forms and the XML metadata, and place them in `data/raw/form` and `data/raw/xml` respectively. Then you can run `src/data/iam_dataset.py` to preprocess the data and `src/data/test_generator.py` to generate test cases.

**Comment by oualidbelhi01** [comment]
yes I understood, the published code is full of fail, I managed to make it work.
What you just said I did but the meta file contains the image path: writer id. I have to fill it in manually from the writers_ids text file.
In the writers_ids file there is a dictionary {image.png, id} of preprocessed images.
You understood me.

**Comment by oualidbelhi01** [comment]
On the code it iterates each line of the meta file and extracts (the image path, writer ids) = info [0] info [1]

**Comment by oualidbelhi01** [comment]
def __init__(self):
        # Read IAM meta data file
        
        meta = open(self.dataset_meta_file, 'r')

        # Read all images with their writers
        for line in meta:
            # Skip comment lines
            if line[0] == '#':
                continue

            # Extract image filename and its writer id
            info = line.split()
            image_path, writer_id = info[0], info[1]

            # If its the first image for the writer, then the writer to the dictionary
            if writer_id not in self.writers:
                self.writers[writer_id] = []

            # Append image filename to its writer entry in the dictionary
            self.writers[writer_id].append(image_path)

        # Close meta data file
        meta.close()

**Comment by OmarBazaraa** [comment]
It has been a long time since we were working on this project, so unfortunately I don't remember that much about the code.
I am not sure whether we wrote `meta.txt` manually or it was provided somewhere in IAM website. But I am inclined toward the fact that we provided our own `meta.txt` manually.

Anyways, you can automate this file easily if you have `xml` files.

**Comment by oualidbelhi01** [comment]
Good,thank you very much
